### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by soulslicer** [ericniebler/meta#43]
Cmake works fine..

but during compilation:

> /home/robotserver/meta/example/tutorial_snippets.cpp:268:5: error: static assertion failed: 
>      static_assert(std::is_same<meta::invoke<t, unsigned>, int const &>{}, "");

**Comment by ericniebler** [comment]
What compiler/version are you using?

**Comment by ericniebler** [comment]
Hello?

**Comment by soulslicer** [comment]
cmake version 3.2.2

g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

**Comment by gnzlbg** [comment]
> g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

@soulslicer Meta requires a "pretty much conforming" C++11 compiler, which for gcc means g++ >= 4.9. 

For some reason this is not in the readme.

**Comment by gnzlbg** [comment]
I quickly added the info that gcc >= 4.9 and clang >= 3.4 are supported to the readme since those are the compilers we actively try to support. 

I wouldn't be surprised if some of them don't work though. I recall some issues with clang 3.5, and GCC 5.x + C++14 + constexpr never quite worked properly.
